spring:
  config:
    import: classpath:/config.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:tcp://${config.db.host}:${db.port}/${db.name}
    username: ${config.db.user}
    password: ${config.db.password}
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    root: DEBUG
server:
  port: ${server.port}
